_unvadmin:
    path:      /unvadmin
    defaults:  { _controller: @AcmeBackendBundle:Default:index }
acme_backend_homepage:
    resource: "@AcmeBackendBundle/Controller/DefaultController.php"
    type: annotation

_secured:
    resource: "@AcmeBackendBundle/Controller/SecuredController.php"
    type:     annotation

_account:
    resource: "@AcmeBackendBundle/Controller/AccountController.php"
    type:     annotation

_ajax:
    resource: "@AcmeBackendBundle/Controller/AjaxController.php"
    type:     annotation

_demo:
    resource: "@AcmeDemoBundle/Controller/DemoController.php"
    type:     annotation
    prefix:   /demo

_frontend:
    resource: "@AcmeFrontendBundle/Controller/DefaultController.php"
    type:     annotation

_article:
    resource: "@AcmeFrontendBundle/Controller/ArticleController.php"
    type:     annotation

_report:
    resource: "@AcmeFrontendBundle/Controller/ReportController.php"
    type:     annotation

_fm_frontend:
    resource: "@AcmeFrontendBundle/Controller/FMController.php"
    type:     annotation

_act:
    resource: "@AcmeFrontendBundle/Controller/ActController.php"
    type:     annotation


random:
     path:     /random/{limit}
     defaults: { _controller: AcmeDemoBundle:Random:index }

_corp:
    resource: "@AcmeBackendBundle/Controller/CorpController.php"
    type:     annotation
_fm:
    resource: "@AcmeBackendBundle/Controller/FMController.php"
    type:     annotation
_admin:
    resource: "@AcmeBackendBundle/Controller/AdminController.php"
    type:     annotation
oneup_uploader:
    resource: .
    type: uploader

elfinder:
     resource: "@FMElfinderBundle/Resources/config/routing.yml"
     prefix: /elfinder

