parameters:
#    acme_backend.example.class: Acme\BackendBundle\Example

services:
#    acme_backend.example:
#        class: %acme_backend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    authentication_handler:
        class: Acme\BackendBundle\Handler\AuthenticationHandler
        calls:
            - [ setContainer, [ @service_container ] ]

    acme_backend.upload_listenr:
        class: Acme\BackendBundle\EventListener\UploadListener
        argument: ['@doctrine']
        tags:
            - { name: kernel.event_listener, event: oneup_uploader.post_persist, method: onUpload }

    acme_core.listener.before_controller:
        class: Acme\CoreBundle\EventListener\BeforeControllerListener
        scope: request
        argument: ['@service.context']
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    acme.twig.acme_extension:
        class: Acme\CoreBundle\Twig\AcmeExtension
        tags:
            - { name: twig.extension }
