security:
    encoders:
        Acme\BackendBundle\Entity\Member:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_FM:          ROLE_USER
        ROLE_CORP:          ROLE_USER
        ROLE_ADMIN:       ROLE_FM, ROLE_CROP
        ROLE_SUPER_ADMIN: [ROLE_FM, ROLE_CROP, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        administrators:
            entity: { class: AcmeBackendBundle:Member }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        _login:
            pattern:  ^/unvadmin/login$
            security: false

        secured_area:
            pattern:    ^/unvadmin
            form_login:
                check_path: _security_check
                login_path: _login
                default_target_path: /unvadmin/index
                always_use_default_target_path: true
                success_handler: authentication_handler
            logout:
                path:   _logout
                target: /
            anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"
        #admin_area:
        #    pattern:    ^/unvadmin
        #    http_basic: ~

    access_control:
        #- { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
        - { path: ^/unvadmin/*, roles: ROLE_USER }
        - { path: ^/unvadmin/admin/*, roles: ROLE_ADMIN }
        - { path: ^/unvadmin/fm/*, roles: ROLE_FM }
        - { path: ^/unvadmin/corp/*, roles: ROLE_CORP }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
