<?php

namespace Acme\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BasicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BasicRepository extends EntityRepository
{
    public function getRankWeekDay()
    {
        return $this->getEntityManager()
            ->createQuery(
            'SELECT b.intWeekDay
                FROM
                AcmeBackendBundle:Basic b
                WHERE b.id = 1'
            )
            ->getSingleScalarResult();
    }
}
