<?php

namespace Acme\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Snc\RedisBundle\Doctrine\Cache\RedisCache;
use Predis\Client;

/**
 * BasicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BasicRepository extends EntityRepository
{
    public function getRankWeekDay($cache_time = 0)
    {
        $query = $this->getEntityManager()
            ->createQuery(
            'SELECT b.intWeekDay
                FROM
                AcmeBackendBundle:Basic b
                WHERE b.id = 1'
            );
        if($cache_time) {
            $predis = new RedisCache();
            $predis->setRedis(new Client());
            $cache_lifetime = $cache_time;
            $query
                ->setResultCacheDriver($predis)
                ->setResultCacheLifetime($cache_lifetime);
        }
        return $query->getSingleScalarResult();
    }
}
