<?php

namespace Acme\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ChampionlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChampionlogRepository extends EntityRepository
{
    public function getArrChampionlog($intZone, $intLimit)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT
                     s.strTitle title,
                     s.arrStrArtistName artists,
                     m.strShortName voter,
                     c.timeDateTime time
                FROM AcmeBackendBundle:Championlog c
                    JOIN AcmeBackendBundle:Song s
                    WITH c.intSongId = s.id
                    JOIN AcmeBackendBundle:Member m
                    WITH c.intMemberId = m.id
                WHERE c.intZone = {$intZone}"
            )
            ->setMaxResults($intLimit)
            ->getResult();
    }
}
