<?php

namespace Acme\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ChampionlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChampionlogRepository extends EntityRepository
{
    public function getObjChampionlog($intType, $intLimit)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT c, s.strTitle, s.arrStrArtist, m.strShortName
                 FROM AcmeBackendBundle:Championlog c
                JOIN AcmeBackendBundle:Song s
                WITH c.intSongId = s.id
                JOIN AcmeBackendBundle:Member m
                WITH c.intMemberId = m.id
                WHERE c.intType = {$intType}"
            )
            ->setMaxResults($intLimit)
            ->getResult();
    }
}
