<?php

namespace Acme\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Snc\RedisBundle\Doctrine\Cache\RedisCache;
use Predis\Client;

/**
 * ForecastRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForecastRepository extends EntityRepository
{
    public function getArrForecastlist($intCount, $cache_time = 0)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                "SELECT f.strContent content,
                        f.timeDateTime time,
                        m.strShortName member_name,
                        f.boolIsUp is_up
                    FROM
                    AcmeBackendBundle:Forecast f
                    JOIN AcmeBackendBundle:Member m
                    WITH f.intMemberId = m.id
                    ORDER BY f.boolIsUp DESC, f.timeDateTime DESC
                    "
            )
            ->setMaxResults($intCount);
        if($cache_time > 0) {
            $predis = new RedisCache();
            $predis->setRedis(new Client());
            $cache_lifetime = $cache_time;
            $query
                ->setResultCacheDriver($predis)
                ->setResultCacheLifetime($cache_lifetime);
        }
        return $query->getResult();
    }
}
