<?php

namespace Acme\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ForecastRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForecastRepository extends EntityRepository
{
    public function getArrForecastlist($intCount)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT f.strContent content,
                        f.timeDateTime time,
                        m.strShortName member_name
                    FROM
                    AcmeBackendBundle:Forecast f
                    JOIN AcmeBackendBundle:Member m
                    WITH f.intMemberId = m.id
                    ORDER BY f.timeDateTime DESC
                    "
            )
            ->setMaxResults($intCount)
            ->getResult();
    }
}
