<?php

namespace Acme\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RankLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RankLogRepository extends EntityRepository
{
    public function getIntCountRanked()
    {
        return $this->getEntityManager()
            ->createQuery(
            'SELECT COUNT(l.id) - 1 FROM AcmeBackendBundle:RankLog l'
            )
            ->getSingleScalarResult();
    }

    public function getIntLatestTermNo()
    {
        return $this->getEntityManager()
            ->createQuery(
            "SELECT l.intTermNo FROM AcmeBackendBundle:RankLog l ORDER BY l.id DESC"
            )
            ->setMaxResults(1)
            ->getSingleScalarResult();
    }
}
