<?php

namespace Acme\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Acme\BackendBundle\Entity\Constant;

/**
 * RankRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RankRepository extends EntityRepository
{
    public function getObjNewestRanklist($intZone, $intType)
    {
        if($intZone == Constant::PRCZONE)
            $strResult = 'intPRCResult';
        else if($intZone == Constant::HKTWZONE)
            $strResult = 'intHKTWResult';
        return $this->getEntityManager()
            ->createQuery(
                "SELECT s.strTitle title,
                        s.arrStrArtistName artists,
                        s.id id,
                        r.intTermNo term_no
                    FROM
                    AcmeBackendBundle:Rank r
                    JOIN r.songs s
                    WHERE r.intZone = {$intZone}
                        and r.intType = {$intType}
                    ORDER BY s.{$strResult} DESC
                    "
            )
            ->setMaxResults(20)
            ->getResult();
    }
}
