<?php

namespace Acme\FrontendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    public function getArrArticleList($intCategory, $intLimit, $strOrderBy, $strOrderType)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT a.id id,
                        a.strTitle title,
                        a.intCategory category,
                        a.strThumb thumb,
                        a.timeCreateTime time
                    FROM AcmeFrontendBundle:Article a
                    WHERE a.intCategory = {$intCategory}
                    ORDER BY a.{$strOrderBy} {$strOrderType}
                "
            )
            ->setMaxResults($intLimit)
            ->getResult();
    }

    public function getQueryArticleList($intCategory, $strWhere)
    {
        return $this->getEntityManager()
            ->createQuery(
            "
                SELECT a.id id,
                       a.strTitle title,
                       a.intCategory category,
                       a.strThumb thumb,
                       a.timeCreateTime time
                 FROM AcmeFrontendBundle:Article a
                WHERE a.intCategory = {$intCategory}
                {$strWhere}
                ORDER BY a.timeCreateTime DESC
            "
            );
    }

}
