<?php

namespace Acme\FrontendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    public function getArrArticlelist($intCategory, $intLimit, $strOrderBy, $strOrderType)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT a FROM AcmeFrontendBundle:Article a
                    WHERE a.intCategory = {$intCategory}
                    ORDER BY a.{$strOrderBy} {$strOrderType}
                "
            )
            ->setMaxResults($intLimit)
            ->getResult();
    }
}
