<?php

namespace Acme\FrontendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CoopRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoopRepository extends EntityRepository
{
    public function getArrCoopList($intLimit)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT c
                    FROM AcmeFrontendBundle:Coop c
                    ORDER BY c.intWeight DESC, c.timeUploadTime DESC
                "
            )
            ->setMaxResults($intLimit)
            ->getResult();
    }
}
