<?php

namespace Acme\FrontendBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Snc\RedisBundle\Doctrine\Cache\RedisCache;
use Predis\Client;

/**
 * CoopRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoopRepository extends EntityRepository
{
    public function getArrCoopList($intLimit, $cache_time = 0)
    {
        $predis = new RedisCache();
        $predis->setRedis(new Client());
        $cache_lifetime = $cache_time;
        return $this->getEntityManager()
            ->createQuery(
                "SELECT c
                    FROM AcmeFrontendBundle:Coop c
                    ORDER BY c.intWeight DESC, c.timeUploadTime DESC
                "
            )
            ->setMaxResults($intLimit)
            ->setResultCacheDriver($predis)
            # set cache lifetime
            ->setResultCacheLifetime($cache_lifetime)
            ->getResult();
    }
}
