<?php

namespace Acme\FrontendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FlashRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlashRepository extends EntityRepository
{
    public function getArrFlashlist()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT f
                    FROM
                    AcmeFrontendBundle:Flash f
                    '
            )
            ->getResult();
    }
}
