<?php

namespace Acme\FrontendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FlashRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlashRepository extends EntityRepository
{
    public function getArrFlashlist($intCategory)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT f
                    FROM
                    AcmeFrontendBundle:Flash f
                    WHERE f.intCategory = {$intCategory}
                    "
            )
            ->getResult();
    }
}
