<?php

namespace Acme\FrontendBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Snc\RedisBundle\Doctrine\Cache\RedisCache;
use Predis\Client;

/**
 * FlashRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlashRepository extends EntityRepository
{
    public function getArrFlashlist($intCategory, $cache_time = 0)
    {
        $predis = new RedisCache();
        $predis->setRedis(new Client());
        $cache_lifetime = $cache_time;
        return $this->getEntityManager()
            ->createQuery(
                "SELECT f
                    FROM
                    AcmeFrontendBundle:Flash f
                    WHERE f.intCategory = {$intCategory}
                    "
            )
            ->setResultCacheDriver($predis)
            # set cache lifetime
            ->setResultCacheLifetime($cache_lifetime)
            ->getResult();
    }
}
