<?php

namespace Acme\FrontendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OtherInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OtherInfoRepository extends EntityRepository
{
    public function getObjFrontendInfo()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT o
                    FROM
                    AcmeFrontendBundle:OtherInfo o
                    '
            )
            ->getResult()[0];
    }
}
