<?php

namespace Acme\FrontendBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Predis\Client;
use Snc\RedisBundle\Doctrine\Cache\RedisCache;

/**
 * OtherInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OtherInfoRepository extends EntityRepository
{
    public function getArrFrontendInfo($cache_time = 0)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT o
                    FROM
                    AcmeFrontendBundle:OtherInfo o
                    '
            );
        if($cache_time > 0) {
            $predis = new RedisCache();
            $predis->setRedis(new Client());
            $cache_lifetime = $cache_time;
            $query
                ->setResultCacheDriver($predis)
                ->setResultCacheLifetime($cache_lifetime);
        }
        return $query->getResult()[0];
    }
}
