parameters:
#    acme_frontend.example.class: Acme\FrontendBundle\Example

services:
#    acme_frontend.example:
#        class: %acme_frontend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
